db_endpoint = "booxwoox.c8cealu7kjd3.ap-south-1.rds.amazonaws.com"
db_username = "admin"
db_password = "11312113"
db_name_user = "users_db"
db_name_blogs = "blogs_db"
db_name_service ="service_db"
aws_access_key_id = "AKIA5HZ6C5CJTY4AYHWL"
aws_secret_access_key = "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"
aws_region = "ap-south-1"
mail_client_username = ""
mail_client_password = ""

rajorpay_secret = "sutxJND6kBZXVmvRvOI4A22E"
rajorpay_key_ID =  "rzp_test_JtUEcv7jC7SyPA"

