AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  booxwoox-backend
  Sample SAM Template for BooxWoox tech
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  
Resources:
  validateotp:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: validateotp
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        validateotp:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /validateotp
            Method: post
      Role: arn:aws:iam::910126409875:role/atm1504