AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: booxwoox-backend Sample SAM Template for BooxWoox tech
Globals:
  Function:
    Timeout: 3
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS'''
        AllowHeaders: '''X-Forwarded-For,Authorization,Content-Type,Accept,authToken,authtoken'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  ApproveBook:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ApproveBook
      CodeUri: s3://booxwoox-lambdas/bda484415955a2d3d8b57a9d7be7eace
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        ApproveBook:
          Type: Api
          Properties:
            Path: /ApproveBook
            Method: POST
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::910126409875:role/atm1504
