AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'booxwoox-backend Sample SAM Template for BooxWoox tech

  '
Globals:
  Function:
    Timeout: 3
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS'''
        AllowHeaders: '''X-Forwarded-For,Authorization,Content-Type,Accept,authToken,authtoken'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  getBookDetail:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get_BookDetail
      CodeUri: s3://booxwoox-lambdas/a69082e633491a66bd898660637ac31f
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        getBookDetail:
          Type: Api
          Properties:
            Path: /sarthak_test/get_bookDetail
            Method: post
      Role: arn:aws:iam::910126409875:role/atm1504
