AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  booxwoox-backend
  Sample SAM Template for BooxWoox tech
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST, GET, OPTIONS'"
        AllowHeaders: "'X-Forwarded-For,Authorization,Content-Type,Accept,authToken,authtoken'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        AllowCredentials: false
  getBookDetail:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: get_BookDetail
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        getBookDetail:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sarthak_test/get_bookDetail
            Method: post

      Role: arn:aws:iam::910126409875:role/atm1504