AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'booxwoox-backend Sample SAM Template for BooxWoox tech

  '
Globals:
  Function:
    Timeout: 3
Resources:
  chooseorder:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: chooseorder
      CodeUri: s3://booxwoox-lambdas/91a1b77093d09ecb9b20c1577ba5d3d8
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        chooseorder:
          Type: Api
          Properties:
            Path: /chooseorder
            Method: post
      Role: arn:aws:iam::910126409875:role/atm1504
